iscsi_offload: fix detection of bnx2i
The iscsi_offload script would fail to properly detect bnx2i
iBFT settings; it would declare all interfaces as ibft.
Also we need to update the interface settings for the
generic interface, too; it'll be used during session pickup.
In addition some script errors have been fixed.

References: bnc#886198

Signed-off-by: Hannes Reinecke <hare@suse.de>
(cherry picked from commit 5d94cce243e101474881027576039f918a087128)

Conflicts:
	utils/iscsi_offload

diff --git a/utils/iscsi_offload b/utils/iscsi_offload
--- a/utils/iscsi_offload
+++ b/utils/iscsi_offload
@@ -101,6 +101,23 @@ iscsi_macaddress_from_pcifn()
     done
 }
 
+update_iface_setting() {
+    local iface="$1"
+    local name="$2"
+    local value="$3"
+
+    iface_value=$(iscsiadm -m iface -I $iface | sed -n "s/$name = \(.*\)/\1/p")
+    if [ "$iface_value" = "<empty>" ] ; then
+	iface_value=
+    fi
+    if [ "$iface_value" != "$value" ] ; then
+	if ! iscsiadm -m iface -I $iface -o update -n "$name" -v "$value" ; then
+	    return 1
+	fi
+    fi
+    return 0
+}
+
 while getopts di:t options ; do
     case $options in
 	d ) mode=dhcp;;
@@ -116,6 +133,7 @@ done
 shift $(($OPTIND - 1))
 
 IFNAME=$1
+ibft_mode="none"
 
 if [ -z "$IFNAME" ] ; then
     echo "No interface specified"
@@ -210,6 +228,7 @@ fi
 gen_iface="$mod.$mac"
 ioe_iface="${IFNAME}-${mod}"
 
+# Get existing settings
 if iscsiadm -m iface -I $ioe_iface > /dev/null 2>&1 ; then
     ioe_mac=$(iscsiadm -m iface -I $ioe_iface 2> /dev/null| sed -n "s/iface\.hwaddress = \(.*\)/\1/p")
     ioe_mod=$(iscsiadm -m iface -I $ioe_iface 2> /dev/null| sed -n "s/iface\.transport_name = \(.*\)/\1/p")
@@ -221,6 +240,7 @@ elif [ "$mod" = "be2iscsi" ] ; then
     ioe_mac=$mac
     ioe_mod=$mod
 else
+    # Create new interface
     iscsiadm -m iface -I $ioe_iface --op=new 2> /dev/null
     ioe_mac=
     ioe_mod=
@@ -232,17 +252,20 @@ if [ -z "$dry_run" ] ; then
 	if [ -n "$ioe_mac" ] ; then
 	    echo "Warning: Updating MAC address on iface $ioe_iface"
 	fi
-	iscsiadm -m iface -I $ioe_iface -o update -n iface.hwaddress -v $mac
+	update_iface_setting $ioe_iface iface.hwaddress "$mac"
     fi
 
     if [ "$ioe_mod" != "$mod" ] ; then
 	if [ -n "$ioe_mod" ] ; then
 	    echo "Warning: Update transport on iface $ioe_iface"
 	fi
-	iscsiadm -m iface -I $ioe_iface -o update -n iface.transport_name -v $mod
+	update_iface_setting $ioe_iface iface.transport_name "$mod"
     fi
 elif [ -z "$ipaddr" ] ; then
     ipaddr=$(iscsiadm -m iface -I $gen_iface 2> /dev/null| sed -n "s/iface\.ipaddress = \(.*\)/\1/p")
+    if [ "$ipaddr" = "<empty>" ] ; then
+	ipaddr=
+    fi
 elif [ "$ioe_mod" != "$mod" ] ; then
     echo "Warning: Transport mismatch on iface $ioe_iface: $ioe_mod should be $mod"
 fi
@@ -263,8 +286,6 @@ if [ -n "$iboot_dir" ] && [ -d "$iboot_dir" ] ; then
 	    ibft_mode="static"
 	elif [ "$ibft_origin" -eq 3 ] ; then
 	    ibft_mode="dhcp"
-	else
-	    ibft_mode="unknown"
 	fi
 	[ -f $if/dhcp ] && read ibft_dhcp < $if/dhcp
 	if [ -n "$ibft_dhcp" -a "$ibft_mode" != "dhcp" ] ; then
@@ -272,6 +293,8 @@ if [ -n "$iboot_dir" ] && [ -d "$iboot_dir" ] ; then
 	fi
 	if [ "$ibft_mode" = "dhcp" ] ; then
 	    ibft_ipaddr="0.0.0.0"
+	    ibft_gateway=
+	    ibft_mask=
 	    break
 	fi
 	[ -f $if/ip-addr ] && read ibft_ipaddr < $if/ip-addr
@@ -287,15 +310,19 @@ fi
 
 # Check if the interface needs to be configured
 if [ -z "$mode" ] ; then
-    if [ "$optaddr" = "$ibft_ipaddr" ] ; then
+    if [ "$ibft_mode" != "none" ] ; then
 	echo "$mac ibft"
-    elif [ "$ipaddr" = "<empty>" ] ; then
+	mode="ibft"
+    elif [ -z "$ipaddr" ] ; then
 	echo "$mac none"
+	mode="none"
     elif [ "$ipaddr" = "0.0.0.0" ] ; then
 	echo "$mac dhcp"
 	ipaddr=
-    else 
+	mode="dhcp"
+    else
 	echo "$mac ip $ipaddr"
+	mode="static"
     fi
     [ "$dry_run" ] && exit 0
 elif [ "$mode" = "dhcp" ] ; then
@@ -313,24 +340,33 @@ if [ "$mod" = "be2iscsi" ] ; then
     exit 4
 fi
 
-if ! iscsiadm -m iface -I $ioe_iface -o update -n iface.ipaddress -v $optaddr ; then
+if ! update_iface_setting $ioe_iface iface.ipaddress "$optaddr" ; then
     echo "Failed to set IP address: $?"
     exit 1
 fi
-if [ "$ibft_mode" = "dhcp" ] ; then
-    iscsiadm -m iface -I $ioe_iface --op=update \
-	--name iface.gateway --value=""
-    iscsiadm -m iface -I $ioe_iface --op=update \
-	--name=iface.subnet_mask --value=""
-elif [ "$ibft_mode" = "static" ] ; then
-    if [ "$ibft_gateway" ] ; then
-	iscsiadm -m iface -I $ioe_iface --op=update \
-	    --name=iface.gateway --value="$ibft_gateway"
-    fi
-    if [ "$ibft_mask" ] ; then
-	iscsiadm -m iface -I $ioe_iface --op=update \
-	    --name=iface.subnet_mask --value=$ibft_mask
-    fi
+if ! update_iface_setting $gen_iface iface.ipaddress "$optaddr" ; then
+    echo "Failed to set IP address for generic interface: $?"
+    exit 1
+fi
+
+if ! update_iface_setting $ioe_iface iface.gateway "$ibft_gateway" ; then
+    echo "Failed to set gateway address: $?"
+    exit 1
+fi
+
+if ! update_iface_setting $gen_iface iface.gateway "$ibft_gateway" ; then
+    echo "Failed to set gateway address for generic interface: $?"
+    exit 1
+fi
+
+if ! update_iface_setting $ioe_iface iface.subnet_mask "$ibft_mask" ; then
+    echo "Failed to set subnet mask: $?"
+    exit 1
+fi
+
+if ! update_iface_setting $gen_iface iface.subnet_mask "$ibft_mask" ; then
+    echo "Failed to set subnet mask for generic interface: $?"
+    exit 1
 fi
 
 if [ "$mod" = "qla4xxx" ] ; then
